import { createAction, props } from '@ngrx/store';
import { CanvasNode, CanvasEdge, AgentGraphSpec, RunEvent } from '../../shared/models/canvas';
export const agentLoaded = createAction('[Canvas] Agent Loaded', props<{agentId:string; graph:AgentGraphSpec}>());
export const nodeAdded = createAction('[Canvas] Node Added', props<{node:CanvasNode}>());
export const nodeMoved = createAction('[Canvas] Node Moved', props<{id:string; position:{x:number;y:number}}> ());
export const nodeConfigUpdated = createAction('[Canvas] Node Config Updated', props<{id:string; config:any; label?:string}>());
export const nodeRemoved = createAction('[Canvas] Node Removed', props<{id:string}>());
export const nodeSelected = createAction('[Canvas] Node Selected', props<{id:string|null}>());
export const edgeAdded = createAction('[Canvas] Edge Added', props<{edge:CanvasEdge}>());
export const edgeRemoved = createAction('[Canvas] Edge Removed', props<{id:string}>());
export const viewportUpdated = createAction('[Canvas] Viewport Updated', props<{viewport:{x:number;y:number;zoom:number}}> ());
export const saveSuccess = createAction('[Canvas] Save Success');
export const runTriggered = createAction('[Run] Triggered');
export const runStarted = createAction('[Run] Started', props<{runId:string}>());
export const runStep = createAction('[Run] Step', props<{event:RunEvent}>());
export const runAwaitingHuman = createAction('[Run] Awaiting Human', props<{event:RunEvent}>());
export const runCompleted = createAction('[Run] Completed', props<{event:RunEvent}>());
export const runFailed = createAction('[Run] Failed', props<{error:string}>());
export const canvasReset = createAction('[Canvas] Reset');
